nome = input('Digite seu nome: ')
print('o tipo primitivo de nome é:', type(nome))
print('Só tem espaços?', nome.isspace())
print('É um número?', nome.isnumeric())
print('É alfabético?', nome.isalpha())
print('É alfanumerico?', nome.isalnum())
print('Está em maiúcula?', nome.isupper())
print('Está em minúscula?', nome.islower())
print('Está capitalizada?', nome.istitle())
