a = str(input('Digite uma frase:')).strip()
frase = a.lower()
print(f'A letra A aparece {frase.count('a')} vezes na frase')
print(f'A primeira letra A apareceu na posicão {frase.find('a') + 1}')
print(f'A ultima letra A apareceu na posicão {frase.rfind('a')+1}')
